import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Header() {
    return (<>
        <Head>
            <title>Compare Cloud ☁️ by Salim Karim</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
            <h1 className={styles.title}>
                Welcome to ☁️ Compare Cloud
            </h1>
            <p className={styles.description}>
                Here we compare the 4 main cloud providers; Amazon AWS, Google GCP, Microsoft Azure and Oracle{' '}
            </p>
        </main>
    </>)
}